### ISSUE TITLE
Support lang attribute on HTML element

### ISSUE THREAD

**Issue by baileyandy** [jsreport/jsreport-base#1]
My template content starts with
```
<!DOCTYPE html>
<html lang="en">
<head>
```

as a lang-less element is considered a warning from the [W3C validator](https://validator.w3.org/). However the [base.js](https://github.com/jsreport/jsreport-base/blob/master/lib/base.js#L1) regex currently does not consider this attribute.

I've removed the `lang` from my template to get this working but it would be great to have support for matching an optional `lang` attribute, since it use is [encouraged](https://www.w3.org/TR/html51/semantics.html#the-html-element).

Updating the regex locally to `/(<html( lang="[a-zA-Z-]*")?>[\s\S]*<head>)/m` has also fixed it for me locally, but I haven't run any of the tests yet.

**Comment by pofider** [comment]
Thank you for suggestion.
It seems that `html` tag can contain also other attributes so I made the regexp more general.
`/(<html.*>[\s\S]*<head>)/`.

This is released in 2.0.1

**Comment by baileyandy** [comment]
Thanks! Upgraded to 2.0.1 and can confirm it solves the problem 👍
