### ISSUE TITLE
Double base using child templates

### ISSUE THREAD

**Issue by baileyandy** [jsreport/jsreport-base#2]
I am using a [child templates](https://github.com/jsreport/jsreport-child-templates) to include a common header for other templates, however this causes the `<base>` to be injected twice - once for the child template and then again when rendering the fully composed template.

Example common header to be included in other templates:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
```

I propose checking if `<base>` already exists and then skip processing, but I am not sure if this would break other use cases of this library.

I also spotted some slightly misleading logging in [base.js](https://github.com/jsreport/jsreport-base/blob/master/lib/base.js#L11) which is output even if no `<base>` was added. For example when base options are set, then rendering a child template that does not match the regex `req.template.content.indexOf(replacedBase)` will return a truthy `-1`.

**Comment by pofider** [comment]
Ah I see thanks.

So we need a check to not add `base` tag when it is already present which makes sense anyway.
And fix the condition `if (req.template.content.indexOf(replacedBase))`.

I will look into it in a next day or if you want you can PR the fix on your own.

**Comment by baileyandy** [comment]
Thanks for the quick response! If I have some free time I'll PR a fix.

**Comment by pofider** [comment]
We are now releasing full jsreport, so I took a look on this and fixed it.
